# Site settings
title: Jiayun Wan
description: Personal page
# baseurl: "" # the subpath of your site, e.g. /blog
url: https://jiayunwan.github.io # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jiayun Wan
user_description: 闻多素心人，乐与数晨夕
email: xxx@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
